server:
  port: 18080


management:
  endpoints:
    web:
      exposure:
        include:
          - "info"
          - "health"
          - "httptrace"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
  client:
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    shouldUnregisterOnShutdown: true

logging.level.root: info