spring:
  rabbitmq:
    addresses: localhost:5672
    username: naver_lecture
    password: test1234
    virtual-host: test-virtual-host
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        publishChannel:
          binder: rabbit
          destination: naver-lecture-test-exchange
          producer:
            required-groups: naver-lecture-test-queue