spring:
  jpa:
    hibernate:
      ddlAuto: update
  datasource:
    url: jdbc:mysql://localhost:3306/commerce_platform?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: test_lecture
    password: test1234