sample:
  data:
    - "[한국 닌텐도] Nintendo Switch 모여봐요 동물의 숲 에디션"
    - "LG전자 그램17 17ZD90N-VX7BK"
    - "주연테크 슈퍼플라이 J7FC_5S"
    - "한성컴퓨터 올데이롱 TFX5470H"
    - "삼성전자 삼성 NT350XCR-AD5WA"
    - "LG전자 그램17 17ZD90N-VX70K"
    - "한성컴퓨터 올데이롱 TFX5470H"
    - "Apple 맥북 프로 16형 2019년형 1T 스페이스 그레이 (MVVK2KH/A)"
    - "ASUS 비보북 R564DA-BQ774"
    - "Apple 맥북 프로 13형 2020년형 256G 스페이스 그레이 (MXK32KH/A)"