spring:
  rabbitmq:
    addresses: localhost:5672
    username: test_lecture
    password: test1234
    virtual-host: test-virtual-host
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        subscribeChannel:
          binder: rabbit
          destination: test-lecture-test-exchange
          group: test-lecture-test-queue
          durableSubscription: true
        deadLetterChannel:
          binder: rabbit
          destination: test-lecture-dead-letter-test-exchange
          producer:
            required-groups: test-lecture-dead-letter-test-queue